// <auto-generated />
using System;
using Blazor_Board.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorBoard.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250716020904_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blazor_Board.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "admin",
                            Content = "掲示板が開かれました！",
                            CreatedAt = new DateTime(2025, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "1番目",
                            UserId = 0
                        },
                        new
                        {
                            Id = 2,
                            Author = "admin",
                            Content = "初めまして",
                            CreatedAt = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "初めまして!",
                            UserId = 0
                        },
                        new
                        {
                            Id = 3,
                            Author = "admin",
                            Content = "Blazor",
                            CreatedAt = new DateTime(2025, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Blazor Board Site",
                            UserId = 0
                        },
                        new
                        {
                            Id = 4,
                            Author = "admin",
                            Content = "いいですね！",
                            CreatedAt = new DateTime(2025, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "いい天気です",
                            UserId = 0
                        },
                        new
                        {
                            Id = 5,
                            Author = "kim",
                            Content = "初めてですね",
                            CreatedAt = new DateTime(2025, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "おはようございます!",
                            UserId = 0
                        },
                        new
                        {
                            Id = 6,
                            Author = "bang",
                            Content = "質問！",
                            CreatedAt = new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "質問があります",
                            UserId = 0
                        });
                });

            modelBuilder.Entity("Blazor_Board.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "管理者",
                            Password = "1234",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "方斗賢",
                            Password = "1234",
                            Role = "User",
                            Username = "bang"
                        },
                        new
                        {
                            Id = 3,
                            Name = "金",
                            Password = "1234",
                            Role = "User",
                            Username = "kim"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
